/* GENERATED FILE - DO NOT EDIT.
 * Produced by tools/gen_error_catalog.py from B_Sharp/Errors/error_catalog.json.
 */

#include "bsharp_catalog_gen.h"

#include <string.h>

const BSharpErrorInfo bsharp_error_catalog[] = {
    {
        "ASN001",
        "Uncaught Assignment Error",
        "Attempting to redefine '{name}' which was already defined",
        "Use a different variable name or remove the existing definition",
    },
    {
        "ASN002",
        "Uncaught Assignment Error",
        "Attempting to access an unassigned variable '{name}'",
        "Declare the variable with 'var' before using it",
    },
    {
        "ASN003",
        "Uncaught Assignment Error",
        "'{name}' is not defined",
        "Declare the variable with 'var' before using it",
    },
    {
        "ASN004",
        "Uncaught Assignment Error",
        "Cannot assign value of type {actual_type} to a variable declared with Empty",
        "Use a compatible type or change the variable declaration",
    },
    {
        "ASN005",
        "Uncaught Assignment Error",
        "Cannot assign value of type {actual_type} to a variable declared with {expected_type}",
        "Ensure the value type matches the variable declaration",
    },
    {
        "ASN006",
        "Uncaught Assignment Error",
        "Tuple value does not match annotation {expected}: {reason}",
        "Provide a tuple with the required length and element types",
    },
    {
        "ASN007",
        "Uncaught Assignment Error",
        "Cannot unpack a tuple of {actual} element(s) into {expected} variable(s)",
        "Declare the same number of variables as there are tuple elements",
    },
    {
        "CMP001",
        "Comparison Syntax Error",
        "Chained comparisons are not supported",
        "Combine separate comparisons with 'and' or 'or' (e.g., 'a < b and b < c')",
    },
    {
        "CMP002",
        "Comparison Syntax Error",
        "Unexpected type for 'and' operation",
        "Both operands must be Boolean types",
    },
    {
        "CMP003",
        "Comparison Syntax Error",
        "Unexpected type for 'or' operation",
        "Both operands must be Boolean types",
    },
    {
        "IMP001",
        "Circular Import Error",
        "Circular import detected: '{file_path}' is already being loaded",
        "Remove the circular dependency between the imported files",
    },
    {
        "LEX001",
        "Illegal Character",
        "Character '{char}' is not allowed in B#",
        "Remove the unsupported character or replace it with a valid B# operator/identifier",
    },
    {
        "LEX002",
        "Double Floating Assigned Error.",
        "A number literal cannot contain more than one decimal point",
        "Use only one decimal point in number literals (e.g., 3.14, not 3.1.4)",
    },
    {
        "MOD001",
        "Uncaught Modification Error",
        "Cannot mutate a const list/array (it is immutable)",
        "Use 'var' instead of 'const' for mutable collections",
    },
    {
        "MOD002",
        "Uncaught Modification Error",
        "Cannot change value of '{name}' of type const",
        "Use 'var' instead of 'const' if you need to reassign this variable",
    },
    {
        "MOD003",
        "Uncaught Modification Error",
        "Cannot modify struct type '{name}' – struct types are immutable",
        "Create an instance via 'var a = Type()' and modify its fields",
    },
    {
        "MOD004",
        "Uncaught Modification Error",
        "Cannot assign to field '{property}' of temporary struct instance",
        "Assign via variable: 'var a = Type(); a.field = value'",
    },
    {
        "MTH001",
        "Unexpected Mathematical Error",
        "Result too large to represent",
        "Use smaller numbers or exponents to avoid overflow",
    },
    {
        "RUN001",
        "RunTime Error",
        "No visitor implemented for node '{node_type}'",
        "This is an internal error - please report it",
    },
    {
        "RUN002",
        "RunTime Error",
        "Unknown binary operator '{operator}'",
        "Check that the operator is supported for the given types",
    },
    {
        "RUN003",
        "RunTime Error",
        "Unary '-' cannot negate {type_name}",
        "Only Number, List, and Inf values can be negated",
    },
    {
        "RUN004",
        "RunTime Error",
        "Unknown unary operator '{operator}'",
        "Check that the operator is valid",
    },
    {
        "RUN005",
        "RunTime Error",
        "Increment/decrement operations are only supported on Number types",
        "Use ++ or -- only on Number variables",
    },
    {
        "RUN006",
        "RunTime Error",
        "'{name}' is not a function",
        "Ensure you are calling a defined function",
    },
    {
        "RUN007",
        "RunTime Error",
        "Maximum call depth exceeded (recursion too deep)",
        "Reduce recursion depth or use iteration instead",
    },
    {
        "RUN008",
        "RunTime Error",
        "Cannot use 'return' outside of a function",
        "Use 'return' only inside function definitions",
    },
    {
        "RUN009",
        "RunTime Error",
        "Unexpected property '{property}' for ErrorInstance",
        "Supported properties: 'name', 'details', 'line', 'file', 'type'",
    },
    {
        "RUN010",
        "RunTime Error",
        "Unexpected property '{property}' for {type_name}",
        "Check the available properties for this type",
    },
    {
        "RUN011",
        "RunTime Error",
        "Index is out of bounds",
        "Ensure the index is within the valid range for this collection",
    },
    {
        "RUN012",
        "RunTime Error",
        "Given type is not indexable",
        "Only List, Array, and String types support indexing",
    },
    {
        "RUN013",
        "RunTime Error",
        "Cannot assign to string index (strings are immutable)",
        "Create a new string instead of modifying an existing one",
    },
    {
        "RUN014",
        "RunTime Error",
        "Target of assignment is not indexable",
        "Only List, Array, and String types support index assignment",
    },
    {
        "RUN015",
        "RunTime Error",
        "Cannot slice this type",
        "Only List, Array, and String types support slicing",
    },
    {
        "RUN016",
        "RunTime Error",
        "Could not import '{file_path}': File not found",
        "Check that the file exists and the path is correct",
    },
    {
        "RUN017",
        "RunTime Error",
        "Failed to read module '{file_path}'",
        "Check file permissions and ensure the file is readable",
    },
    {
        "RUN018",
        "RunTime Error",
        "Failed to tokenize module '{file_path}'",
        "Check for syntax errors in the imported module",
    },
    {
        "RUN019",
        "RunTime Error",
        "Failed to parse module '{file_path}'",
        "Check for syntax errors in the imported module",
    },
    {
        "RUN020",
        "RunTime Error",
        "Symbol(s) not found in module '{file_path}'",
        "Ensure the symbols are exported from the module",
    },
    {
        "RUN021",
        "RunTime Error",
        "{label} must be an integer Number",
        "Convert the value to an integer before using it as an index",
    },
    {
        "RUN022",
        "RunTime Error",
        "'{method}' is not a method of {type_name}",
        "Check the available methods for this type",
    },
    {
        "RUN023",
        "RunTime Error",
        "'{method}' expects {expected} argument(s), got {actual}",
        "Provide the correct number of arguments",
    },
    {
        "RUN024",
        "RunTime Error",
        "'break' outside loop",
        "Use 'break' only inside while, for, or do-while loops",
    },
    {
        "RUN025",
        "RunTime Error",
        "'continue' outside loop",
        "Use 'continue' only inside while, for, or do-while loops",
    },
    {
        "RUN026",
        "RunTime Error",
        "Module '{file_path}' cannot be found",
        "Check that the file exists and the path is correct",
    },
    {
        "RUN027",
        "RunTime Error",
        "Module '{file_path}' exceeds the maximum nesting depth",
        "Reduce the number of nested imports",
    },
    {
        "RUN028",
        "RunTime Error",
        "Function '{func_name}' promises return type '{return_type}' but not all code paths return a value",
        "Ensure every branch in the function ends with 'return <value>'",
    },
    {
        "RUN097",
        "RunTime Error",
        "'{property}' is not a field of struct '{struct_name}'",
        "Check the struct definition for available fields",
    },
    {
        "RUN098",
        "RunTime Error",
        "Cannot instantiate '{type_name}' - not a struct",
        "Only struct types can be instantiated with structName()",
    },
    {
        "RUN099",
        "RunTime Error",
        "Unexpected type for {type_name} {op} operation.",
        "Check that the operation is supported for the given type",
    },
    {
        "RUN100",
        "RunTime Error",
        "Unallowed division by zero",
        "Ensure the divisor is not zero before dividing",
    },
    {
        "RUN101",
        "RunTime Error",
        "'%' integer division requires integer operands",
        "Convert operands to whole numbers before using '%' (integer division)",
    },
    {
        "RUN102",
        "RunTime Error",
        "Unexpected type for non-number types in modulo operation",
        "Ensure both operands are Numbers for '~' (modulo) operations",
    },
    {
        "RUN103",
        "RunTime Error",
        "'~' modulo requires integer operands",
        "Convert operands to whole numbers before using '~' (modulo)",
    },
    {
        "RUN104",
        "RunTime Error",
        "Unallowed modulo by zero",
        "Ensure the divisor is not zero before '~' (modulo) operation",
    },
    {
        "RUN105",
        "RunTime Error",
        "Unallowed division by zero in exponentiation",
        "Cannot compute 0 raised to a negative power",
    },
    {
        "RUN106",
        "RunTime Error",
        "Complex numbers are not yet supported",
        "Avoid operations that would result in complex numbers",
    },
    {
        "RUN107",
        "RunTime Error",
        "String multiplication requires a non-negative integer power factor",
        "Use a positive integer for string repetition",
    },
    {
        "RUN108",
        "RunTime Error",
        "String multiplication requires an integer factor",
        "Convert the multiplier to an integer",
    },
    {
        "RUN109",
        "RunTime Error",
        "Insert index {index} is out of bounds for length {length}",
        "Ensure the index is between 0 and the collection length",
    },
    {
        "RUN110",
        "RunTime Error",
        "Index {index} is out of bounds for length {length}",
        "Ensure the index is within the valid range",
    },
    {
        "RUN111",
        "RunTime Error",
        "List multiplication requires both lists to be the same size",
        "Use lists of equal length for element-wise multiplication",
    },
    {
        "RUN112",
        "RunTime Error",
        "Unsupported type '{type_name}' for list multiplication",
        "Only Number and List types can be multiplied with lists",
    },
    {
        "RUN113",
        "RunTime Error",
        "Division between two lists is not supported",
        "Use scalar division instead",
    },
    {
        "RUN114",
        "RunTime Error",
        "Unsupported type '{type_name}' for list division",
        "Only Number type can divide a list",
    },
    {
        "RUN115",
        "RunTime Error",
        "Expected {expected_type} element, got Empty (none)",
        "Use Empty[] for none values in typed arrays",
    },
    {
        "RUN116",
        "RunTime Error",
        "Expected {expected_type} element, got Empty inside nested list",
        "Ensure all elements match the array type",
    },
    {
        "RUN117",
        "RunTime Error",
        "Expected {expected_type} element, got {actual_type} inside nested list",
        "Ensure all nested elements match the array type",
    },
    {
        "RUN118",
        "RunTime Error",
        "Expected {expected_type} element, got {actual_type}",
        "Ensure the element type matches the array declaration",
    },
    {
        "RUN119",
        "RunTime Error",
        "Unsupported type '{type_name}' for array multiplication",
        "Only Number type can multiply with arrays",
    },
    {
        "RUN120",
        "RunTime Error",
        "Division between two arrays or lists is not supported",
        "Use scalar division instead",
    },
    {
        "RUN121",
        "RunTime Error",
        "Unsupported type '{type_name}' for array division",
        "Only Number type can divide an array",
    },
    {
        "RUN122",
        "RunTime Error",
        "Function '{func_name}' expects {expected} arguments, but got {actual}",
        "Provide the correct number of arguments",
    },
    {
        "RUN123",
        "RunTime Error",
        "Function '{func_name}' returned type {actual_type}, expected {expected_type}",
        "Ensure the function returns the declared type",
    },
    {
        "RUN130",
        "RunTime Error",
        "{function_name}: {error_details}",
        "Check the builtin function documentation for usage",
    },
    {
        "RUN131",
        "RunTime Error",
        "'format' expects at least 1 argument (template string)",
        "Usage: format(template, ...args)",
    },
    {
        "RUN132",
        "RunTime Error",
        "First argument to 'format' must be a String",
        "The template string must be the first argument",
    },
    {
        "RUN133",
        "RunTime Error",
        "read failed: {error_details}",
        "Check that input is available",
    },
    {
        "RUN134",
        "RunTime Error",
        "readln failed: {error_details}",
        "Check that input is available",
    },
    {
        "RUN135",
        "RunTime Error",
        "'{function_name}' expects 1 argument",
        "Provide exactly one argument",
    },
    {
        "RUN136",
        "RunTime Error",
        "Cannot convert '{value}' to a number",
        "Ensure the string represents a valid number",
    },
    {
        "RUN137",
        "RunTime Error",
        "Cannot convert {type_name} to Number",
        "Only String and Number types can be converted to Number",
    },
    {
        "RUN138",
        "RunTime Error",
        "'time' function requires no arguments",
        "Call time() without arguments",
    },
    {
        "RUN139",
        "RunTime Error",
        "Cannot modify a tuple (tuples are immutable)",
        "Reassign the whole variable with a new tuple instead of editing elements",
    },
    {
        "SHD001",
        "Shadowing Error",
        "Parameter name '{param_name}' shadows the function name '{func_name}'",
        "Use a different parameter name to avoid shadowing the function name",
    },
    {
        "SYN001",
        "Syntax Error",
        "Expected an equalizer after NOT logical operation",
        "Use '!=' instead of '!' followed by '='",
    },
    {
        "SYN002",
        "Syntax Error",
        "Invalid escape sequence '\\{char}'",
        "Valid escape sequences are: \\n (newline), \\t (tab), \\\\ (backslash), \\' (quote)",
    },
    {
        "SYN003",
        "Syntax Error",
        "Unterminated string literal, expected closing {quote_char}",
        "Add the closing quote character to complete the string",
    },
    {
        "SYN004",
        "Syntax Error",
        "Unterminated block comment. Expected closing '*/'",
        "Add '*/' to close the block comment",
    },
    {
        "SYN005",
        "Syntax Error",
        "The '**' operator is not defined",
        "Use '^' for exponentiation instead of '**'",
    },
    {
        "SYN006",
        "Syntax Error",
        "Expected ')'",
        "Add a closing parenthesis to complete the expression",
    },
    {
        "SYN007",
        "Syntax Error",
        "Expected int, float, identifier, '+', '-', '(', or keyword",
        "Check the syntax at the indicated position",
    },
    {
        "SYN008",
        "Syntax Error",
        "Expected 'using' keyword to import a module",
        "Use 'using \"filename\"' to import a module",
    },
    {
        "SYN009",
        "Syntax Error",
        "Module import name is expected to be a valid string file path",
        "The import path must be a string: using \"path/to/file\"",
    },
    {
        "SYN010",
        "Syntax Error",
        "Expected 'if'",
        "Use 'if condition then' or 'if condition {{' to start an if statement",
    },
    {
        "SYN011",
        "Syntax Error",
        "Expected 'then' or '{{' after if condition",
        "Use 'if condition then' or 'if condition {{' syntax",
    },
    {
        "SYN012",
        "Syntax Error",
        "Expected 'then' or '{{' after elif condition",
        "Use 'elif condition then' or 'elif condition {{' syntax",
    },
    {
        "SYN013",
        "Syntax Error",
        "Expected ']' after type in array declaration",
        "Close the array type declaration with ']'",
    },
    {
        "SYN014",
        "Syntax Error",
        "Array of List is not supported. Use List for untyped collections.",
        "Use 'List' instead of 'Array[]' for untyped collections",
    },
    {
        "SYN015",
        "Syntax Error",
        "Expected variable identifier name after 'var' or 'const'",
        "Use 'var name' or 'const name' to declare a variable",
    },
    {
        "SYN016",
        "Syntax Error",
        "Expected identifier name after ','",
        "Add a variable name after the comma in multi-variable declaration",
    },
    {
        "SYN017",
        "Syntax Error",
        "Expected type identifier after ':'",
        "Specify the variable type after the colon (e.g., 'var x: Number')",
    },
    {
        "SYN018",
        "Syntax Error",
        "Unknown data type '{type_name}'",
        "Valid types are: Bool, Number, String, Empty, List, Inf, NaN, Function, Number[], String[], Boolean[], Empty[]",
    },
    {
        "SYN019",
        "Syntax Error",
        "Multiple initializers in assignment are not supported",
        "Use a single initializer: 'var x = value'",
    },
    {
        "SYN020",
        "Syntax Error",
        "Uninitialized 'const' declaration requires a value or type",
        "Provide a value or type: 'const x = value' or 'const x: Type'",
    },
    {
        "SYN021",
        "Syntax Error",
        "Expected '[' for creating a list",
        "Start a list with '[' and end with ']'",
    },
    {
        "SYN022",
        "Syntax Error",
        "Expected a valid node inside list",
        "Check the syntax of the list element",
    },
    {
        "SYN023",
        "Syntax Error",
        "Expected ',' or ']' for a list definition",
        "Separate elements with ',' or close the list with ']'",
    },
    {
        "SYN024",
        "Syntax Error",
        "Expected '{{' after 'try'",
        "Start the try block with '{{'",
    },
    {
        "SYN025",
        "Syntax Error",
        "Empty 'try' block is not allowed",
        "Add at least one statement inside the try block",
    },
    {
        "SYN026",
        "Syntax Error",
        "Expected '}}' at end of 'try' block",
        "Close the try block with '}}'",
    },
    {
        "SYN027",
        "Syntax Error",
        "Expected '(' after 'catch'",
        "Use 'catch(ErrorType varName)' syntax",
    },
    {
        "SYN028",
        "Syntax Error",
        "Expected error type name after 'catch('",
        "Specify the error type: catch(Error e)",
    },
    {
        "SYN029",
        "Syntax Error",
        "Unknown error type '{error_type}'",
        "Valid error types are: Error, B_SharpSyntaxError, RunTimeError, AssignmentError, ModificationError, ComparisonError, BSharpMathError, ShadowingError",
    },
    {
        "SYN030",
        "Syntax Error",
        "Expected ')' after catch clause",
        "Close the catch parameter list with ')'",
    },
    {
        "SYN031",
        "Syntax Error",
        "Expected '{{' to start catch block",
        "Start the catch block with '{{'",
    },
    {
        "SYN032",
        "Syntax Error",
        "A 'try' block must be followed by at least one 'catch' clause",
        "Add a catch clause: catch(ErrorType varName)",
    },
    {
        "SYN033",
        "Syntax Error",
        "Expression or block nesting exceeds the maximum depth",
        "Reduce nesting by extracting sub-expressions or simplifying logic",
    },
    {
        "SYN034",
        "Syntax Error",
        "Unexpected token or invalid syntax",
        "Check the syntax at the indicated position",
    },
    {
        "SYN035",
        "Syntax Error",
        "Expected '{{'",
        "Start a block with '{{'",
    },
    {
        "SYN036",
        "Syntax Error",
        "Expected '}}'",
        "Close the block with '}}'",
    },
    {
        "SYN037",
        "Syntax Error",
        "Expected variable identifier after '++' or '--'",
        "Use 'x++' or '--x' with a variable name",
    },
    {
        "SYN038",
        "Syntax Error",
        "Invalid increment/decrement expression",
        "Use 'x++' or '--x' syntax",
    },
    {
        "SYN039",
        "Syntax Error",
        "Expected 'while'",
        "Use 'while condition' to start a while loop",
    },
    {
        "SYN040",
        "Syntax Error",
        "Expected '{{' or 'then' after while condition",
        "Use 'while condition then' or 'while condition {{' syntax",
    },
    {
        "SYN041",
        "Syntax Error",
        "Expected 'do'",
        "Use 'do' to start a do-while loop",
    },
    {
        "SYN042",
        "Syntax Error",
        "Expected '{{' after 'do' statement",
        "Start the do block with '{{'",
    },
    {
        "SYN043",
        "Syntax Error",
        "Expected 'while' after 'do' block",
        "Add 'while condition' after the do block",
    },
    {
        "SYN044",
        "Syntax Error",
        "Expected '(' after 'while' in do/while",
        "Wrap the condition in parentheses: while (condition)",
    },
    {
        "SYN045",
        "Syntax Error",
        "Expected ')' after do/while condition",
        "Close the condition with ')'",
    },
    {
        "SYN046",
        "Syntax Error",
        "Expected 'for'",
        "Use 'for (init; condition; update)' to start a for loop",
    },
    {
        "SYN047",
        "Syntax Error",
        "Expected '(' after 'for'",
        "Wrap the for loop header in parentheses",
    },
    {
        "SYN048",
        "Syntax Error",
        "Expected ';' after for loop initializer",
        "Separate for loop parts with ';'",
    },
    {
        "SYN049",
        "Syntax Error",
        "Expected ';' after for loop condition",
        "Separate for loop parts with ';'",
    },
    {
        "SYN050",
        "Syntax Error",
        "Expected ')' after for loop header",
        "Close the for loop header with ')'",
    },
    {
        "SYN051",
        "Syntax Error",
        "Expected '{{' or 'then' after for loop expression",
        "Start the for loop body with '{{' or 'then'",
    },
    {
        "SYN052",
        "Syntax Error",
        "Expected property or method name",
        "Add a property or method name after the '.'",
    },
    {
        "SYN053",
        "Syntax Error",
        "Expected closing brackets ']'",
        "Close the index or slice with ']'",
    },
    {
        "SYN054",
        "Syntax Error",
        "Expected ')' or ','",
        "Separate arguments with ',' or close the call with ')'",
    },
    {
        "SYN055",
        "Syntax Error",
        "Expected ',' or ')'",
        "Separate arguments with ',' or close the call with ')'",
    },
    {
        "SYN056",
        "Syntax Error",
        "Expected 'fn' or 'function'",
        "Use 'fn name()' or 'function name()' to define a function",
    },
    {
        "SYN057",
        "Syntax Error",
        "Unallowed calling of a function by a keyword",
        "Use a different name that is not a keyword",
    },
    {
        "SYN058",
        "Syntax Error",
        "Expected function identifier after function name",
        "Provide a name for the function",
    },
    {
        "SYN059",
        "Syntax Error",
        "Expected '(' after function name",
        "Add parentheses for parameters: fn name(params)",
    },
    {
        "SYN060",
        "Syntax Error",
        "Expected parameter name identifier",
        "Add a parameter name (e.g., 'fn func(x: Number)')",
    },
    {
        "SYN061",
        "Syntax Error",
        "Expected type identifier after ':'",
        "Specify the parameter type (e.g., 'x: Number')",
    },
    {
        "SYN062",
        "Syntax Error",
        "Duplicate parameter name '{param_name}' in function '{func_name}'",
        "Use unique parameter names within a function",
    },
    {
        "SYN063",
        "Syntax Error",
        "Expected ',' or ')' in parameter list",
        "Separate parameters with ',' or close with ')'",
    },
    {
        "SYN064",
        "Syntax Error",
        "Unknown return type '{return_type}'",
        "The type you committed is not a valid type.",
    },
    {
        "SYN065",
        "Syntax Error",
        "Expected return type identifier after '->'",
        "Specify the return type: -> ReturnType",
    },
    {
        "SYN066",
        "Syntax Error",
        "Expected '{{' to start function body block",
        "Start the function body with '{{'",
    },
    {
        "SYN067",
        "Syntax Error",
        "Expected 'return'",
        "Use 'return value' to return from a function",
    },
    {
        "SYN068",
        "Syntax Error",
        "Expected a caller macro after exclamation.",
        "Use on of the predefined caller macros.",
    },
    {
        "SYN069",
        "Syntax Error",
        "Caller macros must appear at the top of the file, before any code.",
        "Move all '!pragma' lines to the file header before any statements",
    },
    {
        "SYN070",
        "Syntax Error",
        "Expected 'struct'",
        "Use 'struct Name { ... }' to define a struct",
    },
    {
        "SYN071",
        "Syntax Error",
        "Expected struct name identifier",
        "Provide a name for the struct: struct Name { ... }",
    },
    {
        "SYN072",
        "Syntax Error",
        "Expected '{{' after struct name",
        "Start the struct body with '{{'",
    },
    {
        "SYN073",
        "Syntax Error",
        "Only variable declarations are allowed inside struct",
        "Structures may not include any non-variable definition code blocks",
    },
    {
        "SYN074",
        "Syntax Error",
        "Unknown caller macro '{name}'.",
        "Use one of the predefined caller macros (e.g. 'pragma').",
    },
    {
        "SYN075",
        "Syntax Error",
        "'!pragma enforce' requires a type annotation for '{var_names}'.",
        "Declare variables with an explicit type: 'var x : Number = ...'",
    },
    {
        "SYN076",
        "Syntax Error",
        "'!pragma enforce' requires a type for parameter '{param}' of '{func}'.",
        "Declare function parameters with an explicit type: '(value : Number)'",
    },
    {
        "SYN077",
        "Syntax Error",
        "'!pragma enforce' requires function '{func}' to declare a return type.",
        "Add '-> Type' (use '-> Empty' for procedures that return nothing)",
    },
    {
        "SYN078",
        "Syntax Error",
        "Invalid argument for 'precision'. Expected an integer from 0 to 12 or 'default'.",
        "Usage: '!pragma precision 4' or '!pragma precision default'",
    },
    {
        "SYN079",
        "Syntax Error",
        "Caller macro '{name}' does not take arguments.",
        "Remove the argument (e.g. '!pragma enforce')",
    },
    {
        "SYN080",
        "Syntax Error",
        "Unknown pragma directive '{name}'.",
        "Known directives: 'enforce', 'precision'",
    },
    {
        "SYN081",
        "Syntax Error",
        "Malformed tuple type annotation: {reason}",
        "Valid forms: Tuple, Tuple(), Tuple(Number), Tuple(4 : Number), Tuple(Number, String), Tuple(2 : Number, 3 : String)",
    },
    {
        "WRN001",
        "Unreachable Code",
        "Unreachable code after 'return' in function '{func_name}'",
        "Remove or guard the unreachable code after 'return'",
    },
    {
        "WRN002",
        "Precision Loss",
        "Huge power {base}^{exponent} approximated as float; precision may be lost",
        "Consider using smaller exponents or a big-integer library",
    },
};

const size_t bsharp_error_catalog_count = sizeof(bsharp_error_catalog) / sizeof(bsharp_error_catalog[0]);

const BSharpErrorInfo* bsharp_lookup_error(const char* code) {
    if (!code) return NULL;
    size_t lo = 0;
    size_t hi = bsharp_error_catalog_count;
    while (lo < hi) {
        size_t mid = lo + (hi - lo) / 2;
        int cmp = strcmp(code, bsharp_error_catalog[mid].code);
        if (cmp == 0) return &bsharp_error_catalog[mid];
        if (cmp > 0) lo = mid + 1;
        else hi = mid;
    }
    return NULL;
}
